service: dota-discord-bot
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  versionFunctions: false # optional, default is true

functions:
  dota-discord-bot-match-puller:
    handler: src/index.handler
    name: dota-discord-bot-match-puller
    description: Pulls played match details in the last 10 minutes
    memorySize: 128
    timeout: 60
    events:
      - schedule:
          rate: rate(10 minutes)

package:
  patterns:
    - '!./**'
    - '!.yarn/**'
    - './src/**'
    - './node_modules/**'
